backend:
  name: git-gateway
  branch: master
  repo: "cgroark/tm-coaching" # repo where your content lives
  auth_endpoint: "https://tm-coaching-admin.netlify.app/auth"

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/home.json"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Intro Text", name: "intro", widget: "text" }
